CREATE DATABASE MvcDemoDb

USE MvcDemoDb

CREATE TABLE Empleados (
Id UNIQUEIDENTIFIER PRIMARY KEY,
Nombre NVARCHAR(MAX) NOT NULL,
Email NVARCHAR(MAX) NOT NULL,
Nacimiento DATETIME2(7) NOT NULL,
Sueldo BIGINT NOT NULL,
Puesto NVARCHAR(MAX) NOT NULL)